"""create likes table

Revision ID: 60898d6f6435
Revises: 244b4ee9e033
Create Date: 2024-12-12 01:06:17.207546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60898d6f6435'
down_revision = '244b4ee9e033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('player_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
